### ISSUE TITLE
USER STORY: As a Site User I want to be able to register for an account so that I can have an account and a profile.

### ISSUE THREAD

**Issue by YasmineBB** [YasmineBB/curated#1]
EPIC: User Registration and Profile

As a **Site User** I can **register for an account** so that **I can have an account and profile**.

**Acceptance Criteria**
- [ ] User can register with their name, email address and password

**Tasks**
- [ ] Task 1: Set up allauth
- [ ] Task 2:  Check admin panel to see that users registration info is being saved
