### ISSUE TITLE
EPIC #2 USER STORY: As a Site Admin I want to be able to remove products from the site so that only available items are listed.

### ISSUE THREAD

**Issue by YasmineBB** [YasmineBB/curated#10]
EPIC: <epic>

As a **Site Admin** I can **delete products** so that **only available products are listed**.

**Acceptance Criteria**
- [x] Superuser can delete products from the front end when logged in
- [ ]
- [ ]

**Tasks**
- [x] Task 1 : Create view to delete product
- [x] Task 2 : Add buttons on product and product detail page so admin can delete the product
- [x] Task 3 : Test- delete an existing product and check it is not listed
