### ISSUE TITLE
USER STORY: As a Site User I want to be able to sort and filter my search so that I can quickly find what I am looking for.

### ISSUE THREAD

**Issue by YasmineBB** [YasmineBB/curated#12]
EPIC: Product Viewing and Navigation

As a **Site User** I can **sort and filter my search** so that **I can quickly find what I'm looking for**.

**Acceptance Criteria**
- [ ] User can sort by 
- [ ] User can search a term and is shown related products
- [ ] Correct products are shown according to sorting/searching/filtering

**Tasks**
- [ ] Task 1 : Add search bar and button
- [ ] Task 2 : Test search feature
- [ ] Task 3 :
