### ISSUE TITLE
USER STORY: As a Site user I want to be able to search keywords so that I can quickly find what I am looking for.

### ISSUE THREAD

**Issue by YasmineBB** [YasmineBB/curated#13]
EPIC: Product Viewing and Navigation

As a **Site User** I can **search keywords** so that **I can quickly find what I am looking for**.

**Acceptance Criteria**
- [ ] User can search key words and are shown related products
- [ ]
- [ ]

**Tasks**
- [ ] Task 1 : Add search bar 
- [ ] Task 2 : Test search functionality - are they returning the desired results
- [ ] Task 3 :
