### ISSUE TITLE
As a Site User I want to be able to edit and delete items from my basket so that I can decide on my final purchase.

### ISSUE THREAD

**Issue by YasmineBB** [YasmineBB/curated#17]
EPIC: Shopping Basket and Purchasing

As a **Site User** I can **edit and delete items from my basket** so that **I can decide on my final purchase**.

**Acceptance Criteria**
- [ ] User can delete an item from their basket
- [ ] User is displayed a message alert confirming the action
- [ ] User is displayed a message that their basket is empty and prompted to continue shopping

**Tasks**
- [ ] Task 1 :
- [ ] Task 2 :
- [ ] Task 3 :
