### ISSUE TITLE
USER STORY: As a Site User I want to be able to view a profile of an artist so that  can find out more about the artist whose work I am interested in and make a more informed decision on purchasing

### ISSUE THREAD

**Issue by YasmineBB** [YasmineBB/curated#18]
EPIC: Artist Profile

As a **Site User** I can **view an artist profile** so that **I can find out more about the artist whose work I am interested in and make a more informed decision on purchasing**.

**Acceptance Criteria**
- [ ] User can click on the artists name and is taken to the artists profile page
- [ ] Artist profile has the artists name, bio, profile picture, location and links to socials
- [ ]

**Tasks**
- [ ] Task 1 : Create Artist model
- [ ] Task 2 : Link artists to their products
- [ ] Task 3 : Create and style templates for artist profile view
