### ISSUE TITLE
USER STORY: As a Site Admin I want to be be able to create profiles for new and existing artists so that users can find out more about the artists whose work they are interested in

### ISSUE THREAD

**Issue by YasmineBB** [YasmineBB/curated#19]
EPIC: Artist Profile

As a **Site Admin** I can **create profiles for new and existing artists** so that **users can find out more about the artists whose work they are interested in**.

**Acceptance Criteria**
- [ ] Site admin can add new profiles from the admin panel
- [ ] 
- [ ]

**Tasks**
- [ ] Task 1 : Create Artist app and model
- [ ] Task 2 : Add a new profile with all information and check it is displayed correctly
- [ ] Task 3 :
