### ISSUE TITLE
USER STORY: As a Site User I want to be able to login and out so that I can keep my information secure.

### ISSUE THREAD

**Issue by YasmineBB** [YasmineBB/curated#2]
EPIC: Registration and Profile

As a **Site User** I can **log in and out** so that **I can keep my information secure**.

**Acceptance Criteria**

- [ ] User can successfully login with information used in registration
- [ ] User can log out successfully 
- [ ] User received message alert for both log in and out

**Tasks**

- [ ] Task 1: Set up allauth
- [ ] Task 2 : Add and style log in/out buttons in navigation
- [ ] Task 3 : Add message alerts on log in and out
