### ISSUE TITLE
EPIC #5 USER STORY: As a Site Admin I want to be able to edit artist profiles so that I can make changes if needs be.

### ISSUE THREAD

**Issue by YasmineBB** [YasmineBB/curated#20]
EPIC: Artist Profile

As a **Site Admin** I can **edit artist profiles** so that **I can make changes or updates if needs be**.

**Acceptance Criteria**
- [x] Site admin can make changes to an existing artist profile from the admin panel and front end
- [x] Updates are correctly reflected on the site
- [ ]

**Tasks**
- [x] Task 1 : Create edit artist view and functionality to only allow for superuser access
- [x] Task 2 : Create template and add edit/delete buttons on artist detail view
- [ ] Task 3 :
