### ISSUE TITLE
EPIC #4 USER STORY: As a Site User I want to be able to make a purchase on the site so that I can buy and enjoy the items I had in my basket.

### ISSUE THREAD

**Issue by YasmineBB** [YasmineBB/curated#22]
EPIC: Purchasing

As a **Site User** I can **make a purchase** so that **I can buy and enjoy the items I had in my basket**.

**Acceptance Criteria**
- [ ] Oder placed is shown in Stripe and database
- [ ] User is taken to order success page confirming purchase
- [ ]

**Tasks**
- [ ] Task 1 : Set up Stripe
- [ ] Task 2 : Test webhooks
- [ ] Task 3 : Error handling
- [ ] Task 4: Make dummy orders and check both webhooks are successful in Stripe and orders are in database from admin panel
