### ISSUE TITLE
EPIC #6 USER STORY: As a Site User I want to be able to submit a contact form so that I can communicate with the platform.

### ISSUE THREAD

**Issue by YasmineBB** [YasmineBB/curated#24]
EPIC: Contact Form

As a **Site User** I can **submit a contact form** so that **I can communicate with the platform**.

**Acceptance Criteria**
- [ ]
- [ ]
- [ ]

**Tasks**
- [ ] Task 1 : Create contact form
- [ ] Task 2 : Test by submitting a form
- [ ] Task 3 : Set up error handling
