### ISSUE TITLE
EPIC #7 USER STORY: As a Site User I want to be able to view testimonials from other customers so that I can make an informed decision on using the site and purchasing

### ISSUE THREAD

**Issue by YasmineBB** [YasmineBB/curated#25]
EPIC: Testimonial

As a **Site User** I can **view testimonials** so that **I can make an informed decision on using the site and making a purchase**.

**Acceptance Criteria**
- [ ] Testimonials that are added my admin are visible on testimonial page
- [ ] Correct information is shown
- [ ]

**Tasks**
- [ ] Task 1 : Create testimonial model
- [ ] Task 2 : Create templates to display testimonials
- [ ] Task 3 :
