### ISSUE TITLE
EPIC #7 USER STORY: As a Site Admin I want to be able to add a testimonial so that users can view them and are encouraged to use the platform and make purchases.

### ISSUE THREAD

**Issue by YasmineBB** [YasmineBB/curated#26]
EPIC: Testimonials

As a **Site Admin** I can **add a testimonial** so that **users can view them and are encouraged to use the platform and make purchases.**.

**Acceptance Criteria**
- [ ] Site admin is able to add all required information
- [ ] Testimonial is saved and displayed correctly
- [ ]

**Tasks**
- [ ] Task 1 : Add a testimonial in admin panel
- [ ] Task 2 : Check it is displayed
- [ ] Task 3 :
