### ISSUE TITLE
As a Site Admin I want to be able to add a testimonial/feature so that users can view them and are encouraged to use the platform and make purchases.

### ISSUE THREAD

**Issue by YasmineBB** [YasmineBB/curated#27]
EPIC: Features/Testimonials

As a **Site Admin** I can **add a testimonial/feature** so that **users can view them and are encouraged to use the platform and make purchases.**.

**Acceptance Criteria**
- [ ] Admin can select feature management from nav bar and taken to a page to add a product
- [ ] Admin can add a feature successfully
- [ ] Feature is displayed on Featured page

**Tasks**
- [ ] Task 1 : Add view to add feature
- [ ] Task 2 : Create url and template
- [ ] Task 3 : Test it works
