### ISSUE TITLE
EPIC #7 USER STORY -As a Site Admin I want to be able to edit a testimonial/feature so that any mistakes can be rectified or images changed.

### ISSUE THREAD

**Issue by YasmineBB** [YasmineBB/curated#28]
EPIC: Features/Testimonials

As a **Site Admin** I can **edit a testimonial/feature** so that **any mistakes can be rectified or images changed.**.

**Acceptance Criteria**
- [ ] Admin has the option to edit the feature when logged in
- [ ] Any changes are successfully reflected on the site
- [ ] 

**Tasks**
- [ ] Task 1 : Add urls and template
- [ ] Task 2: Add section under template for when admin is logged in with link to edit
- [ ] Task 3 : Create view to edit a feature
- [ ] Task 4 : Test it works
