### ISSUE TITLE
EPIC #7 USER STORY -As a Site Admin I want to be able to delete a testimonial/feature so that the features will always fit the purpose of the site goals.

### ISSUE THREAD

**Issue by YasmineBB** [YasmineBB/curated#29]
EPIC: Features/Testimonials

As a **Site Admin** I can **delete a testimonial/feature** so that **the features will always fit the purpose of the site goals.**.

**Acceptance Criteria**
- [ ] Admin can delete the feature when logged in
- [ ] Feature no longer exists on the site
- [ ]

**Tasks**
- [ ] Task 1 : Add view to delete the feature
- [ ] Task 2 : Test it works
- [ ] Task 3 :
