### ISSUE TITLE
USER STORY: As a Site User I want to be able to reset my password so that I can recover and access my account if I forget the password.

### ISSUE THREAD

**Issue by YasmineBB** [YasmineBB/curated#3]
EPIC: User Registration and Profile

As a **Site User** I can **reset my password** so that **I can recover and access my account if I forget the password**.

**Acceptance Criteria**

- [ ] User can follow link to reset their password
- [ ] User can change their password and recover their account
- [ ] User can login with new password

**Tasks**

- [ ] Task 1: 
- [ ] Task 2:
