### ISSUE TITLE
EPIC # 6 USER STORY: As a Site Admin I want to be able to view a list of customer enquiries so that I can see what consumers are wanting to know.

### ISSUE THREAD

**Issue by YasmineBB** [YasmineBB/curated#30]
EPIC: Contact

As a **Site Admin** I can **capability** so that **received benefit**.

**Acceptance Criteria**
- [ ] Admin can select to view customer enquiries from the nav bar when logged in and is taken to the page
- [ ]
- [ ]

**Tasks**
- [ ] Task 1 : Create enquiries view
- [ ] Task 2 : Create template to list the name, email address, subject if one and message
- [ ] Task 3 : Test all the info displays to admin
