### ISSUE TITLE
USER STORY: As a Site User I want to be able to view my profile so that I can save my personal details and see my order history.

### ISSUE THREAD

**Issue by YasmineBB** [YasmineBB/curated#4]
EPIC User Registration and Profile

As a **Site User** I can **view my profile** so that **I can save my personal details and see my order history.**.

**Acceptance Criteria**

- [ ] User can view their profile
- [ ] User can save and update their personal/shipping details
- [ ] User can view all previous orders they have made on the site after logging in

**Tasks**

- [ ] Task 1: Create profile app
- [ ]
