### ISSUE TITLE
USER STORY: As a Site User I want to be able to easily view unique pieces so that I can decide whether I want to add to my basket.

### ISSUE THREAD

**Issue by YasmineBB** [YasmineBB/curated#5]
EPIC: Product Viewing and Site Navigation

As a **Site User** I can **view unique pieces** so that **I can decide whether I want to add to my basket.**.

**Acceptance Criteria**
- [ ] User can view all products
- [ ] User can see required images, product name and price
- [ ] User can view all products clearly on different devices

**Tasks**
- [ ] Task 1 : Set up Products app
- [ ] Task 2 : Create products model and views
- [ ] Task 3 : Create products template
