### ISSUE TITLE
USER STORY: As a Site User I want to be able to easily navigate from one page to another so that I can have a pleasant shopping experience.

### ISSUE THREAD

**Issue by YasmineBB** [YasmineBB/curated#6]
EPIC: <epic>

As a **Site User** I can **easily navigate from one page to another** so that **I can have a pleasant shopping experience**.

**Acceptance Criteria**
- [ ] Navigation is clear and intuitive across all devices
- [ ] All links work
- [ ] 

**Tasks**
- [ ] Task 1 : Create main nav and mobile nav templates
- [ ] Task 3 : Ensure no broken links and error handling
