### ISSUE TITLE
USER STORY: As a Site User I want to be able to view the details of a product so that I can decide whether I want to make a purchase.

### ISSUE THREAD

**Issue by YasmineBB** [YasmineBB/curated#7]
EPIC: Product Viewing and Navigation

As a **Site User** I can **view the details of a product** so that **I can decide whether I want to make a purchase**.

**Acceptance Criteria**
- [ ] User is taken to the desired product detail page of the product they clicked on
- [ ] User can view the item in more detail including image, price, photo, artist information
- [ ]

**Tasks**
- [ ] Task 1 : Create product detail template
- [ ] Task 2 : 
- [ ] Task 3 :
