### ISSUE TITLE
EPIC #2 USER STORY: As a Site Admin I want to be able to add products to the site so that users are able to browse and buy.

### ISSUE THREAD

**Issue by YasmineBB** [YasmineBB/curated#8]
EPIC: Product Viewing and Navigation

As a **Site Admin** I can **add products to the site** so that **users are able to browse and buy**.

**Acceptance Criteria**
- [x] Superuser can add products in the admin panel and front end when logged in
- [x] Products they have added are present on the site with all correct information
- [ ]

**Tasks**
- [x] Task 1 : Manually add products 
- [x] Task 2 : Source stock images for products
- [x] Task 3 : Add products and check items are presented to user
